# Generated by Django 5.0.1 on 2024-08-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessementApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assess_student',
            name='Total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
