# Generated by Django 5.1.1 on 2024-11-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessementApp', '0005_remove_absencereport_stu_indexnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmaster',
            name='phoneNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='headmaster',
            name='phoneNumber',
            field=models.IntegerField(),
        ),
    ]
