# Generated by Django 5.1.1 on 2024-11-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessementApp', '0006_alter_formmaster_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headmaster',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
